version: "3.4"
services:
 vite_docker:
   image: node:alpine
   container_name: vite_docker
   entrypoint: /bin/sh
   ports:
     - 8010:8000
   working_dir: /srv/app
   command : -c "npm install && npm run dev"
   volumes:
     - type: bind
       source: ./
       target: /srv/app
   tty: true