version: '3'

services:
  server:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: ./Dockerfile
      target: server
    volumes:
      - .:/srv/app
    links:
      - php
    ports:
      - '8888:80'
    env_file:
      - .env.local
      
  php:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: ./Dockerfile
      target: php_dev
    volumes:
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/.config/composer:/home/prod/.composer
      - .:/srv/app
      
  database:
    image: postgres:15.4-alpine
    environment:
      POSTGRES_DB: symfony
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8088:8080

  ###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: ["1025:1025", "1080:1080"]
###< symfony/mailer ###

volumes:
  database_data:
